### ISSUE TITLE
OSError : corrupt snappy compressed data

### ISSUE THREAD

**Issue by NamisMe** [FacePerceiver/LAION-Face#4]
Hi, thanks for sharing data.
an Error "OSError : Corrupt snappy compressed data" occured.
Other sites says it is conflict of version (1 and 2) (https://issues.apache.org/jira/browse/ARROW-6057), but there is no solution.
![image](https://user-images.githubusercontent.com/88610815/210475075-ac0799b3-2030-4c2d-a9dd-8fbe0eda2d0c.png)

How can we solve this ?

_Originally posted by @NamisMe in https://github.com/FacePerceiver/LAION-Face/issues/2#issuecomment-1370428956_

**Comment by yinglinzheng** [comment]
I think you might download a corrupted metadata, maybe you should try download again and evaluate the completeness of these parquet file.
