### ISSUE TITLE
The height and width columns are wrong

### ISSUE THREAD

**Issue by offchan42** [FacePerceiver/LAION-Face#6]
![image](https://user-images.githubusercontent.com/15215732/232282982-feca23c5-36fd-43fb-93a9-7aab9230325e.png)
Here is the first part of 400M dataset. I checked the image at index 2 and here is its url: https://farm1.staticflickr.com/784/40182677504_27d67600f3_o.jpg

If you check the image, it's a wide image. But the table says that the height is 800 and width is 512.
It seems the with and height are swapped.

Also some images have changed. (Just FYI, this is unrelated to the Height and width column bug)
For example, the image at index: 12933522 has changed to something else completely. This might indicate that you might need to update the metadata file sometimes in the future.

**Comment by yinglinzheng** [comment]
Maybe you should report the issue to the LAION-400M dataset, instead of LAION-Face dataset.
