### ISSUE TITLE
The face metadata contain images that do not have any faces

### ISSUE THREAD

**Issue by offchan42** [FacePerceiver/LAION-Face#7]
![image](https://user-images.githubusercontent.com/15215732/232283494-906cdf39-f222-4833-89b4-4ff1dda56663.png)
This is the URL of the image at index 3:
https://t2.ftcdn.net/jpg/00/58/35/35/240_F_58353522_3plS29kylx1KZQ0lU6pYHuCAhUINvCSp.jpg

It's a picture of a knee! And it's literally the first image in the file. Is this a bug from the way you detected faces or am I doing something wrong?

**Comment by yinglinzheng** [comment]
This is expected as we use a facial detection system for the detection, and false positives are inevitable. the dataset itself would be noisy.

**Comment by offchan42** [comment]
OK. Understood. Thanks.
